travis:
  secure:
    BINSTAR_TOKEN: Qd/IpOgoyzL9u2Eyc3OC0b9XuIQZFAaWC6FJuEgJAHznRTxBAKxg0xklc4hKtEc+lkAOQVSrScKQWdbeoWi1PZNbiKtsy4TkjiLd+JyDvc9r2VlW7oBpoStzY4miTCyUXoFUSto+wVO3GJX6qzTf8CNk6uoQYpG76ekrVcPWU4KRdW+uirFYRM1UptkpNg3jotgLpToVLzATOM8rC3CS/JC7D6pb1+gKVavbJfkb8gxuBiHi2GGVEYtu1ti26GcUxt/JpYVOzFr14tUD8hg5VCL1bFROOYQihTWlk0jleUu/ocT1OxhTaWxQJqwGq2dhjQX2/LlkncG4MFRDo9OiEE2JcPD7wmQH1C6d6o99wjZGxP8gfNi4OzvHFFIgVE5w3tu5c6x/KFGqkc2Qd+hDsk4kJ1KpkBt6tcuvWiOmWkouVd9BzD8cloJkSQMlxjVs7yssICEa3z2yu392K1CGLMjVgnyPE/ftXkgJykDdU8AINIVhxEh4TwA5gFlXWuvO9MDVY20VRngXchl+chx0FTVBaNra9vw0nbWq4Q8E8GXvUtg1NzfKGG5XF9MtYhgFk1IR+kFpv80zKr9pJXlNNvbdNKBnPt7xYNfTaqdx4uz0mh5gzRLpMwmg7sV4r3ZQz2rV89V6DhQXqPl8qij5uD2lwdR7gagCGag+UFPuVCs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
