travis:
  secure:
    BINSTAR_TOKEN: YyIrUee6FRc/k5wCRlQ0fNCv4bIDPdILv60SIFQFhvscCFZOl5smxCa0/++MAhgI/MrnBK4Fac2vjPqufulbdJfdBAT/85t3ukdvo9YnVK5E+t+28HZqmuDnbJGlFcwQfIKJxXU1ARqyUi8wmCENzq6qzNvFfJdHni0KxvcTfi84wM0m6wyzpgoY9Pd3+4KoEHKhpJgJANULa/OXUBqoFFh8Ymg+0DbGN/hs/fyCJvLBV48Il9TI+1XVRqedJjSnI1gYJZhXxICLBOD6iC3LN9QQGbPkdkkeAnsGetjMZWlUp3zyP+4baabpJRCbqJBJonCWI/InyEfG/QPID4xKUt+RZT1wCuXEj6s2jV9wMRPK2Wlxt8Va1JGb8flxRYlUQOhE0e1INVE8I42NtM2RGNn2eKkeKrvnpDE8ucVRKipikQifaT6I9fD4fsx3lCm1AteTmLEMz2RxR5qlpjUtQUYwcW3XW2lT+NNG1kL8/dY8xKXPOyUWZ39nus7zv4DXm2xSENpHhoMspI0jOkL1Kza77ZApLEimGik745KlCOyFkRYaWH3XF4dkKIbsQEP6R2PTSwXCwB4h2zPp/2kem36iTCgvs1T3smOma++1yypdvE4xlfXA0GRwRpjIaS2mkNIddxabee89BuoNmICdSiPLkjweDpL8MDcGatHBHKc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
